CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(60) NOT NULL,
  description VARCHAR(300) NOT NULL,
  price DECIMAL(5,2) NOT NULL,
  flavor VARCHAR(20) NOT NULL,
  allergen VARCHAR(100) NOT NULL,
  icon VARCHAR(250) NOT NULL 
);
